version: '3.9'

services:
  db:
    image: postgres:17-alpine
    container_name: finance_db
    restart: always
    environtments:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: finance_db
    ports:
      - "5432-5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  migrate:
    image: gomicro/goose
  
  app:
    build: .
    container: finance-svc
    ports:
      - "8080:8080"
    environtments:
      - DSN=postgres://user:postgres123@localhost:5432/finance_db
      - SERVICE_NAME=finance-system
      - APP_VERSION=v1
      - LOG_LEVEL=debug
      - HTTP_PORT=8080
    depends_on:
      - db
    networks:
      - finance_net

volumes:
  pg_data:

networks:
  finance_net:
    driver: bridge
      